# FROM nginx:1.27-alpine

# COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
# COPY docker/web-entrypoint.sh /docker-entrypoint.d/40-runtime-config.sh
# COPY dist /usr/share/nginx/html

# RUN chmod +x /docker-entrypoint.d/40-runtime-config.sh

# EXPOSE 80



FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:1.27-alpine
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY docker/web-entrypoint.sh /docker-entrypoint.d/40-runtime-config.sh
COPY --from=build /app/dist /usr/share/nginx/html

RUN chmod +x /docker-entrypoint.d/40-runtime-config.sh

EXPOSE 80
